### ISSUE TITLE
PID calculation issue

### ISSUE THREAD

**Issue by bk79** [bradquick/bradwii#3]
looking at the Derivative factor calculation I've noticed that you are just subtracting the actual value to the final output, I'll take as example the attitude pid inside bradwii.cpp but I've seen that the same applies also for the other pids:

```
   "  // do the attitude pid
     pidoutput[x]=lib_fp_multiply(angleerror[x],usersettings.pid_pgain[x])
        -lib_fp_multiply(global.gyrorate[x],usersettings.pid_dgain[x])  
        +(lib_fp_multiply(integratedangleerror[x],usersettings.pid_igain[x])>>4);"
```

  "-lib_fp_multiply(global.gyrorate[x],usersettings.pid_dgain[x])  " 
global.gyrorate is the straight value from the gyro reading, but actually the calculation for the derivative term should be (considering the derivative kick fix) "- (actualgyrovalue - lastgyrovalue)"
so translated into something that would apply to your code would be
"
fixedpointnum gyrorateprevious[3]; //to be added in the global structure"

 "-lib_fp_multiply(((global.gyrorate[x]-global.gyrorateprevious[x])/deltacycle),usersettings.pid_dgain[x])  " // inside bradwii.cpp"

"global.gyrorateprevious=global.gyrorate // inside gyro.cpp just before the new reading

**Comment by bradquick** [comment]
I'm doing the pid on position, not velocity, so the derivative is the
velocity, which is what the gyro outputs.

**Comment by bk79** [comment]
got it that's the direct measure from the sensor, so no need to have other calculation on that, I did just focused on that without reading that the P part is on the angle and not coming from gyro
